### ISSUE TITLE
Corrections sur le script d'install'

### ISSUE THREAD

**Issue by Guerout-Arnaud** [raphaelMrci/Epigen#3]
Hello, voila quelques petites modifs que je te conseil concernant l'install

https://github.com/raphaelMrci/Epigen/blob/addfed86aa91454bb411d8f1a270e4c454b54927/install_epitech_gen.sh#L33
Evite les majs

https://github.com/raphaelMrci/Epigen/blob/addfed86aa91454bb411d8f1a270e4c454b54927/install_epitech_gen.sh#L62
pourquoi 777 ?  -> ton user n'a pas besoin de le modif 655 largement suffisant et comme en C evite les valeur, utilise `chmod +x` et ses alternatives

https://github.com/raphaelMrci/Epigen/blob/addfed86aa91454bb411d8f1a270e4c454b54927/install_epitech_gen.sh#L62
Utilise pas `path/lib` mais plutot `path/share`. `/lib` contient les binaire que gcc, clang, etc va chercher pour compliler tes programmes. 
`/share` est utiliser pour stoquer tes programmes/donnees qui n'ont pas besoin d'etre modif (genre les fichier de config tu les mets dans `/var` pas dans `/share`)

https://github.com/raphaelMrci/Epigen/blob/main/epigen
pas besoin de faire un ficher bash utilise un symbolic link (`man ln` si je me plante pas )

J'ai pas reussi a le retrouver et j'ai la flemme de plus chercher mais il y tool pour faire les install de facon plus "automatique" et "ordonnee". j'avais trouver ca quand je cherchais a faire une rule install pour un makefile.

Dernieres choses plus en rapport avec le Repo en lui meme, 
Ajoute un template pour tes issues. 
Traduit le readme en Anglais. Epitech n'est pas present que en france. Des teks non francophones pourraient tomber sur ton repo. Voit grand des le debut ;)

Bon courage

**Comment by raphaelMrci** [comment]
Super!! Merci beaucoup, je vais voir tout ça plus en détail.

Je t'avoue que je me suis grandement inspiré du code de Bubulle Norminette pour l'installeur et la position des fichiers. Bubulle est installé aussi dans la lib, ce qui de ce que tu me dis est une faute, ce qui fait que je me suis donc inspiré d'un amalgame d'erreurs ? On dirait bien. Bon, je vais corriger tout ça rapidement, merci beaucoup
